version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r6-data-app
    ports:
      - "${PORT:-8080}:80"
    env_file:
      - .env
    restart: unless-stopped
